### ISSUE TITLE
Debug P2P network disconnects

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#11]
We just had a 3-way tawk.space with Travis, Myself, and Ethan, where suddenly Ethan could no longer see or hear me:

  1. Ethan was the last person to join. He joined in a new solo group, then moved himself to the combined group of Me and Travis.
  2. Soon after he joined our group, my picture froze for Ethan, and he could not hear me. However, all other audio/video streams were working.
  3. I moved myself out to make my own group. Then I disappeared altogether for Ethan, and Travis and I could still see and hear everyone.
  4. Then I reloaded the page, and all streams went back up.

@karth295 Can you help me generate some hypotheses for what went wrong here? Is it true that there was a P2P stream from my client to Ethan's client, and perhaps that stream went down?

I'm happy to own this issue (just self-assigned) if I can ask you questions and get your expertise.

**Comment by karth295** [comment]
Ack -- I have no intuition on this. It's probably worth looking in the Janus logs and in the browser console to see if any errors pop up.

**Comment by toomim** [comment]
Is it true that there was a P2P stream from my client to Ethan's client, and perhaps that stream went down? Or do all streams go through the server? (I forgot the technical term for it.)
