### ISSUE TITLE
Sometimes Travis's video stream gets delayed

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#16]
This isn't a big deal, because his audio is still in realtime and in sync, but if I watch his video, I'll see his mouth move like a couple seconds after the words were emitted. :P

**Comment by toomim** [comment]
Looks like this might be due to @tkriplean using an old version of chrome. He upgraded chrome an hour ago and we haven't noticed it since. If this continues to be fine, we can close this. :)

**Comment by toomim** [comment]
I'll just mark this closed, and unclose it if it pops up again.

**Comment by karth295** [comment]
If it pops up again, you should try using another webrtc video chat service to figure out whether tawk is at fault.
