### ISSUE TITLE
Tawk doesn't work in Edge

### ISSUE THREAD

**Issue by karth295** [invisible-college/tawk.space#29]
You can see yourself, but not others.

Theory: we use a deprecated syntax for `<video>` tags

```
video.src = URL.createObjectURL(media_stream)
```

When we should be using:

```
video.srcObject = media_stream
```

**Comment by karth295** [comment]
Firefox seems to work now (upgrading did the trick for me) -- editing the title.

**Comment by karth295** [comment]
So it turns out Janus doesn't support Edge, and their [videoroomtest](https://janus.conf.meetecho.com/videoroomtest.html) doesn't work in Edge. Local video appears for a second, and then disappears. No remote streams can be accessed. I see the same issue in tawk right now when I try it in Edge.

**Comment by karth295** [comment]
Jitsi also does not support Edge. It turns out MS created their own standard called ORTC that is similar to -- but not perfectly compatible with -- WebRTC.

**Comment by karth295** [comment]
For now, we should resolve this issue by throwing up a warning in unsupported browsers.

**Comment by toomim** [comment]
Ok.
