### ISSUE TITLE
Video should be toggleable and/or default to off

### ISSUE THREAD

**Issue by karth295** [invisible-college/tawk.space#3]
Video streams are expensive: requiring significant bandwidth (~300kbps per stream) and can't tolerate jittery streams very well. We should allow people to turn their video off, and replace it with a picture or avatar.

@ppham suggested that he'd leave tawk open in the background if it were audio-only, but wouldn't want to broadcast his video unless he was actively using it.

**Comment by toomim** [comment]
It'd be interesting if when you toggle it off, it just _freezes_ with a still frame from your feed. Then you could make a funny face or something.

**Comment by learner-long-life** [comment]
Upvote! Potentially also upload a starcraft-like animated avatar gif

**Comment by karth295** [comment]
@toomim @cryptogoth 

Do either of these look good to you? I imagine that the default behavior for turning off video is freezing your video, and you can click the link button to make a custom image.

http://jsfiddle.net/jj30Lbcf/1/

http://jsfiddle.net/tg4s84m9/2/

**Comment by toomim** [comment]
I think tg4s84m9/2 is better. However, you're using a "volume output" icon instead "microphone" aka "volume input" icon.

I don't think providing a custom image is valuable enough to justify an additional button in the UI.
