### ISSUE TITLE
Scaling isn't right for groups > size 4

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#33]
The scaling works perfectly for 1, 2, 3, or 4 people. But when I have 5 people in a chat, there's extra whitespace over on the right. And when I have 8 people, it gets reallllyyy tiny:
![image](https://user-images.githubusercontent.com/101208/33795083-87cca822-dc8e-11e7-872e-7a5a5253eed4.png)

That's a bit too small.

**Comment by karth295** [comment]
Ah the fallback height for groups of > 6 changed: https://github.com/invisible-college/tawk.space/commit/83a75712a84517c3f682bc64d593099a658a4c06.

I'll generalize scaling instead of special casing small numbers of people.

**Comment by karth295** [comment]
Fixed in https://github.com/invisible-college/tawk.space/commit/f247bffce47e2d9a0fbde90915e7201a0d6f1d16
