### ISSUE TITLE
Chrome doesn't round the video's corners anymore

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#40]
Weird, Chrome now fails to round the videochat corners properly:

![image](https://user-images.githubusercontent.com/101208/67136705-06776600-f1df-11e9-835d-b7c961e70f37.png)

That's Chrome on the left and Firefox on the right.

Is Chrome the new IE?

**Comment by karth295** [comment]
Seems to work for me -- maybe it's fixed now?

**Comment by toomim** [comment]
You're right, I haven't seen this anymore since.

**Comment by karth295** [comment]
Oh I see somebody (maybe you?) changed it in tawk.coffee directly on `https://tawk.space` without committing it to github:

```
$ git diff
diff --git a/client/tawk.coffee b/client/tawk.coffee
index 386e5bc..f4ea00c 100644
--- a/client/tawk.coffee
+++ b/client/tawk.coffee
@@ -339,6 +339,7 @@ dom.PERSON = ->
               width: '100%'
               zIndex: -1
               opacity: .9999 # http://stackoverflow.com/questions/5736503
+              borderRadius: 1
       else
         DIV
           style:
```

I'll just check that into github.

**Comment by toomim** [comment]
Ooohhh... that looks like me! I probably did that during a meeting, and forgot to check it in. I'm embarrassed, but also grateful for your investigation and help! Thank you!

**Comment by karth295** [comment]
Lol all good
