### ISSUE TITLE
Other WebRTC libraries?

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#42]
I've been talking with @canadaduane who is building a game that runs in a web page (with WASM + Javascript), and is trying to add a WebRTC video chat to it. I've been telling him what I know about the available tech, but I think @karth295 knows a little more than me.

We've had some issues with video chat bugs, and although some of them seem to be browser bugs (because they crash the browser, require a browser restart to fix, or only appear on some browsers), I also saw some bugs in Meetecho's product that looked like Meetecho bugs, because the UI itself just wasn't working.

So we have been wondering about other WebRTC libraries. Karthik mentioned Twilio, which I think would be cool to try. Duane also just made this list. He is interested in trying out pion. It looks like it's 2 years old.

> **Open Source:**
> [Pion](https://github.com/pion/webrtc) - seems to be most popular
> [Janus](https://janus.conf.meetecho.com/docs/index.html) - built by meetecho & chosen by tawk.space
> [Simple Peer](https://github.com/feross/simple-peer) - built for p2p and most popular in that category
> [Kurento](https://github.com/Kurento/kurento-media-server) - another popular server
> [WebRTC-Experiment](https://github.com/muaz-khan/WebRTC-Experiment) - lots of popular experiments with WebRTC, reliability unknown
>
>
> **Closed Source:**
> [Whereby](https://whereby.dev/http-api/#/paths/~1meetings/post) - Chris' suggestion
> [Twilio](https://www.twilio.com/webrtc) - Michael's suggestion
> 
> 
> **Noteworthy:**
> [Complex State Machine](https://news.ycombinator.com/item?id=19024330)
> [Popularity of Various WebRTC Projects on Github](https://webrtchacks.com/webrtc-open-source-most-popular/)

**Comment by karth295** [comment]
Yeah it depends on whether you want peer-to-peer video chat, or for video streams to go through a server. For tawk, we want an SFU to relay video streams to avoid creating a high-bandwidth mesh network among clients. While Janus and Kurento seem to be reasonably well used, I think the most popular open source SFU is [Jitsi](https://github.com/jitsi/jitsi-videobridge).

If I recall correctly, you'll also want a TURN server as a fallback for clients who can't do peer-to-peer.  E.g. https://github.com/coturn/coturn

Either way I'm going to close this as slightly irrelevant to tawk.

**Comment by toomim** [comment]
Oh, I opened this because I thought tawk was considering switching to a different SFU, to see if we might have fewer bugs and quirks. I recall Karthik suggesting Twilio earlier.

Is that true, K?

**Comment by toomim** [comment]
@jakearmendariz might be interested in these other WebRTC libraries

**Comment by toomim** [comment]
Here are some notes on the reliability of whereby vs. zoom:

![image](https://user-images.githubusercontent.com/101208/77261130-86e83a00-6c49-11ea-9557-766b7bb76bd8.png)

(From [here](https://twitter.com/Ouren/status/1241398181205889024))

These people are saying that whereby has problems scaling to many participants. I'm thinking we might be able to solve that with servers compositing multiple videos into a single stream. @jakearmendariz.

**Comment by joe-getcouragenow** [comment]
> Here are some notes on the reliability of whereby vs. zoom:
> 
> ![image](https://user-images.githubusercontent.com/101208/77261130-86e83a00-6c49-11ea-9557-766b7bb76bd8.png)
> 
> (From [here](https://twitter.com/Ouren/status/1241398181205889024))
> 
> These people are saying that whereby has problems scaling to many participants. I'm thinking we might be able to solve that with servers compositing multiple videos into a single stream. @jakearmendariz.

@toomim Pion SFU remediates some of the scaling issues : https://github.com/pion/ion-sfu

We are using it and its been great.

**Comment by toomim** [comment]
Thanks @joe-getcouragenow. I've had the same experiences with whereby and zoom. It's good to hear that Pion is working well for you!

How did you run across tawk.space, and what are you up to?
