### ISSUE TITLE
Lots of feedback lately

### ISSUE THREAD

**Issue by toomim** [invisible-college/tawk.space#7]
Something seems to have changed recently (changes in chrome? change in janus?) and we get lots of feedback when tawk.spacing. I even get some feedback (sounds like a "reverb" effect) when I'm alone in a tawk.space and using headphones, so it seems like it's not even physical feedback but some kind of internal feedback.

**Comment by karth295** [comment]
Recently as in days or weeks? I remember the commit that added the volume bar caused problems that I don't remember if I resolved: https://github.com/invisible-college/tawk.space/commit/f0ac9494d9de317656ce7f888e5ec1fed3dc4d98.

Essentially I pass the AV streams through `hark`, which notifies us every 200ms what the current volume is. It has a boolean for whether to actually play the audio or not. I'm passing false to hark for local streams, and true for remote streams.

That actually might be a separate bug--I don't want to play all localstreams, only the ones that are in my group or I'm hovering over.

I commented out the hark/volume bar stuff on https://tawk.space. Can you check whether that fixed the problem?

**Comment by toomim** [comment]
Thanks. I tried testing just now, but I'm unable to even see myself when I open https://tawk.space.

Recently as in 1-8 weeks.

**Comment by toomim** [comment]
Tawk.space isn't asking my permission to use camera/microphone.

**Comment by karth295** [comment]
Fixed in 304c12fe5c26f495b467d6fe0e7f44ff9607d401
